- hosts: localhost
  become: yes
  vars: 
    device: /dev/sda
  tasks:

    - name: Create a new primary partition for boot
      parted:
        device: /dev/sda
        number: 1
        label: gpt
        flags: [ esp ]
        state: present
        part_end: 260MiB

    - name: Create a new primary partition for root
      parted:
        device: /dev/sda
        number: 2
        label: gpt
        state: present
        part_start: 260MiB
        part_end: 1GiB
      
    - name: Create a new primary partition for home
      parted:
        device: /dev/sda
        number: 3
        label: gpt
        state: present
        part_start: 1GiB
        part_end: 2GiB
            
    - name: Create a new primary partition for fun
      parted:
        device: /dev/sda
        number: 4
        label: gpt
        state: present
        part_start: 2GiB
        part_end: 3GiB
      
    # - name: Clear Drive
    #   register: clear_drive
    #   filesystem:
    #     dev: "{{ device }}" 
    #     fstype: ext4
    #     force: yes    
    
    # - debug:
    #     msg: Cleat drive":" {{ clear_drive }}    
 
    # - name: Boot Partition
    #   register: boot_part
    #   parted:
    #     device: "{{ device }}" 
    #     flags: [ esp ]
    #     label: gpt
    #     name: efi
    #     number: 1
    #     part_type: primary
    #     part_end: "260MiB"
    #     unit: MiB
    #     state: present

    # - debug:
    #     msg: Boot partition":" {{ boot_part }}

    # - name: Root Partition
    #   register: root_part
    #   parted:
    #     device: "{{ device }}" 
    #     flags: [ root ]
    #     label: gpt
    #     name: root
    #     number: 2
    #     part_type: logical
    #     part_start: "260MiB"
    #     part_end: "50%"
    #     unit: "MiB"
    #     state: present

    # - debug: 
    #     msg: Root partition":" {{  root_part }}

