- hosts: localhost
  become: yes
  tasks:
  
    - name: Cear Drive
      register: clear_drive
      filesystem:
        dev: /dev/sdb
        fstype: ext4
        
    - debug:
        msg: Cleat drive":" {{ clear_drive }}    
 
    - name: Boot Partition
      register: boot_part
      parted:
        device: /dev/sda
        flags: esp
        label: gpt
        name: efi
        number: 1
        part_end: "260MiB"
        unit: MiB
        state: present

    - debug:
        msg: Boot partition":" {{ boot_part }}

    - name: Root Partition
      register: root_part
      parted:
        device: /dev/sda
        label: gpt
        name: root
        number: 2
        part_start: "260MiB"
        part_end: "50%"
        unit: "MiB"
        state: present

    - debug: 
        msg: Root partition":" {{  root_part }}

