- hosts: localhost
  become: yes
  vars: 
    device: /dev/sda
  tasks:

    - name: Partition disk
      parted:
        device: /dev/sda
        number: 1
        label: gpt
        state: present

    - name: Create a new primary partition for boot
      parted:
        device: /dev/sda
        number: 1
        label: gpt
        flags: [ esp ]
        state: present
        part_end: 260MiB

    - name: Create a new primary partition for root
      parted:
        device: /dev/sda
        number: 2
        label: gpt
        state: present
        part_start: 260MiB
        part_end: 100GiB
      
    - name: Create a new primary partition for swap
      parted:
        device: /dev/sda
        number: 3
        label: gpt
        flags: [ swap ]
        state: present
        part_start: 100GiB
        part_end: 104GiB
            
    - name: Create a new primary partition for home
      parted:
        device: /dev/sda
        number: 4
        label: gpt
        state: present
        part_start: 104GiB
      
    - name: Format boot
      filesystem:
        dev: /dev/sda1
        fstype: vfat   

    - name: Format root
      filesystem:
        dev: /dev/sda2
        fstype: ext4

    - name: Format swap
      filesystem:
        dev: /dev/sda3
        fstype: swap

    - name: Format home
      filesystem:
        dev: /dev/sda4
        fstype: ext4

    - name: Enable swap
      command: swapon /dev/sda3