- hosts: localhost
  become: yes
  tasks:
    
    - name: Boot Partition
      register: boot_part
      parted:
        device: /dev/sda
        flags: esp
        label: gpt
        name: efi
        number: 1
        part_end: "260MiB"
        unit: MiB
        state: present

    - debug:
        msg: Boot partition":" {{ boot_part }}

