- hosts: localhost
  become: yes
  vars: 
    device: device
    boot_number: 1
    root_number: 2
    swap_number: 3
    home_number: 4
  tasks:

    - name: Partition disk
      parted:
        device: device
        number: boot_number
        label: gpt
        state: present

    - name: Create a new primary partition for boot
      parted:
        device: device
        number: boot_number
        label: gpt
        flags: [ esp ]
        state: present
        part_end: 260MiB

    - name: Create a new primary partition for root
      parted:
        device: device
        number: root_number
        label: gpt
        state: present
        part_start: 260MiB
        part_end: 100GiB
      
    - name: Create a new primary partition for swap
      parted:
        device: device
        number: swap_number
        label: gpt
        flags: [ swap ]
        state: present
        part_start: 100GiB
        part_end: 104GiB
            
    - name: Create a new primary partition for home
      parted:
        device: device
        number: home_number
        label: gpt
        state: present
        part_start: 104GiB
      
    - name: Format boot
      filesystem:
        dev: "{{device}} {{boot_number}}"
        fstype: vfat   

    - name: Format root
      filesystem:
        dev: "{{device}} {{root_number}}"
        fstype: ext4

    - name: Format swap
      filesystem:
        dev: "{{device}} {{swap_number}}"
        fstype: swap

    - name: Format home
      filesystem:
        dev: "{{device}} {{home_number}}"
        fstype: ext4

    - name: Enable swap
      command: "swapon {{ swap_number }}"