- hosts: localhost
  become: yes
  vars: 
    device: /dev/sda
  tasks:
  
    - name: Clear Drive
      register: clear_drive
      filesystem:
        dev: "{{ device }}" 
        fstype: ext4
        force: yes    
    
    - debug:
        msg: Cleat drive":" {{ clear_drive }}    
 
    - name: Boot Partition
      register: boot_part
      parted:
        device: "{{ device }}" 
        flags: [ esp ]
        label: gpt
        name: efi
        number: 1
        part_end: "260MiB"
        unit: MiB
        state: present

    - debug:
        msg: Boot partition":" {{ boot_part }}

    - name: Root Partition
      register: root_part
      parted:
        device: "{{ device }}" 
        label: gpt
        name: root
        number: 2
        part_start: "260MiB"
        part_end: "50%"
        unit: "MiB"
        state: present

    - debug: 
        msg: Root partition":" {{  root_part }}

