- hosts: localhost
  become: yes
  vars: 
    device: /dev/sda
  tasks:

    # - name: Clear Drive
    #   register: clear_drive
    #   filesystem:
    #     dev: "{{ device }}" 
    #     fstype: fat32
    #     force: yes    

    - name: Create a new primary partition with a size of 1GiB
      parted:
        device: /dev/sda
        label: gpt
        flags: [ esp ]
        number: 1
        state: present
        part_end: 1GiB

    - name: Create a new primary partition for LVM
      parted:
        device: /dev/sda
        label: gpt
        number: 2
        flags: [ root ]
        state: present
        part_start: 1GiB
  
    # - name: Clear Drive
    #   register: clear_drive
    #   filesystem:
    #     dev: "{{ device }}" 
    #     fstype: ext4
    #     force: yes    
    
    # - debug:
    #     msg: Cleat drive":" {{ clear_drive }}    
 
    # - name: Boot Partition
    #   register: boot_part
    #   parted:
    #     device: "{{ device }}" 
    #     flags: [ esp ]
    #     label: gpt
    #     name: efi
    #     number: 1
    #     part_type: primary
    #     part_end: "260MiB"
    #     unit: MiB
    #     state: present

    # - debug:
    #     msg: Boot partition":" {{ boot_part }}

    # - name: Root Partition
    #   register: root_part
    #   parted:
    #     device: "{{ device }}" 
    #     flags: [ root ]
    #     label: gpt
    #     name: root
    #     number: 2
    #     part_type: logical
    #     part_start: "260MiB"
    #     part_end: "50%"
    #     unit: "MiB"
    #     state: present

    # - debug: 
    #     msg: Root partition":" {{  root_part }}

